//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestEntities : DbContext
    {
        public TestEntities()
            : base("name=TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_RASTREABILIDADMATRIZ_Result> SP_RASTREABILIDADMATRIZ(string pA_CBPARTNER_ID_MATRIZ, string pA_TIENDA)
        {
            var pA_CBPARTNER_ID_MATRIZParameter = pA_CBPARTNER_ID_MATRIZ != null ?
                new ObjectParameter("PA_CBPARTNER_ID_MATRIZ", pA_CBPARTNER_ID_MATRIZ) :
                new ObjectParameter("PA_CBPARTNER_ID_MATRIZ", typeof(string));
    
            var pA_TIENDAParameter = pA_TIENDA != null ?
                new ObjectParameter("PA_TIENDA", pA_TIENDA) :
                new ObjectParameter("PA_TIENDA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RASTREABILIDADMATRIZ_Result>("SP_RASTREABILIDADMATRIZ", pA_CBPARTNER_ID_MATRIZParameter, pA_TIENDAParameter);
        }
    }
}
